language: go
go:
 - 1.11.x

before_script:
 - go get -t -v -u ./...

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
 - bash <(curl -s https://codecov.io/bash) -t "0d098d50-872f-4694-b14b-6a3a49cba5b1"